version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_lab_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Оце і є "підмонтовувати робочу папку"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastapi_lab_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"